name: woof
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.3.0
  table_calendar: ^3.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # ðŸ”‘ Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.4   # â¬…ï¸ ADICIONE

  # ðŸ“· SeleÃ§Ã£o de imagens
  image_picker: ^1.1.2        # â¬…ï¸ ADICIONE

  # ðŸ“¦ Gerenciamento de estado (GetX)
  get: ^4.7.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
